### ISSUE TITLE
Fix Airflow environment variables for the ingestion pipeline  

### ISSUE THREAD

**Issue by anghelalexandra** [Morphl-AI/MorphL-Model-User-Search-Intent#7]
Error log for `run_ingestion.sh`:

```
Running command: docker run --rm -v /opt/secrets:/opt/secrets:ro -v /opt/usi_csv:/opt/usi_csv:ro -e MORPHL_SERVER_IP_ADDRESS -e MORPHL_CASSANDRA_USERNAME -e MORPHL_CASSANDRA_KEYSPACE -e MORPHL_CASSANDRA_PASSWORD -e USI_GOOGLE_CLOUD_PROJECT -e USI_GOOGLE_CLOUD_BUCKET -e USI_GOOGLE_CLOUD_PROCESSED -e USI_GOOGLE_CLOUD_UNPROCESSED -e USI_GOOGLE_CLOUD_SERVICE_ACCOUNT pythoncontainer bash /opt/usi_csv/ingestion/run_ingestion.sh 
Already up-to-date.
/opt/anaconda/lib/python3.6/site-packages/gcsfs/core.py:280: UserWarning: GCS project not set - cannot list or create buckets
warnings.warn('GCS project not set - cannot list or create buckets')
Traceback (most recent call last):
File "/opt/code/ingestion/ingestion.py", line 40, in <module>
main()
File "/opt/code/ingestion/ingestion.py", line 36, in main
data_ingestion.run()
File "/opt/code/ingestion/ingestion.py", line 22, in run
for csv_path in self.storage_manager.get_unprocessed_filenames():
File "/opt/code/ingestion/gs_manager.py", line 28, in get_unprocessed_filenames
return self.get_filenames(self.USI_GOOGLE_CLOUD_UNPROCESSED)
File "/opt/code/ingestion/gs_manager.py", line 20, in get_filenames
csv_full_paths = self.fs.ls(self.USI_GOOGLE_CLOUD_BUCKET + '/' + path_in_bucket)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Command exited with return code 1
```

**Comment by anghelalexandra** [comment]
Possible fix - reload environment variables for user `airflow` before triggering the Airflow DAG.
